// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLENoKsH62xu3eS-ccrCrhXcfQ6zUQDA8',
    appId: '1:343383265863:web:e4f882e388435fc4bdd762',
    messagingSenderId: '343383265863',
    projectId: 'apnastay-f5379',
    authDomain: 'apnastay-f5379.firebaseapp.com',
    storageBucket: 'apnastay-f5379.firebasestorage.app',
    measurementId: 'G-VBHPQ9SPG1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6B7EdeHxgUrtvo5UB_hwV9IKChOCQjiM',
    appId: '1:343383265863:ios:0c93685325a4caacbdd762',
    messagingSenderId: '343383265863',
    projectId: 'apnastay-f5379',
    storageBucket: 'apnastay-f5379.firebasestorage.app',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-HLkaOvRUWqVDn73p0_HRElmSp8pInjE',
    appId: '1:343383265863:android:276fdce58aa7966abdd762',
    messagingSenderId: '343383265863',
    projectId: 'apnastay-f5379',
    storageBucket: 'apnastay-f5379.firebasestorage.app',
  );
}
